### ISSUE TITLE
1.5.0 release depends on non-stable versions

### ISSUE THREAD

**Issue by cap10morgan** [joshwnj/json-mode#36]
Thanks for the 1.5.0 release in MELPA Stable!

However, it currently isn't installable if you solely rely on MELPA Stable as it depends on non-stable versions of its dependencies.

Could it work with json-reformat 0.0.5 (released on Oct. 7, 2015)?

json-snatcher has no stable versions tagged yet, but I've [opened an issue over there](https://github.com/Sterlingg/json-snatcher/issues/8) to see if the author wouldn't mind doing that.

**Comment by markhellewell** [comment]
I hit this one too.  I much prefer sticking to melpa-stable :)

**Comment by joshwnj** [comment]
Thanks @cap10morgan, good find. I'll push a new stable tag once json-snatcher is updated.

**Comment by bostonaholic** [comment]
:+1: Yes. This is _killing_ me right now.

**Comment by markhellewell** [comment]
After poking around the author’s repos I think [json-snatcher](https://github.com/Sterlingg/json-snatcher) might be abandoned :(

**Comment by cap10morgan** [comment]
@markhellewell That's not good. @joshwnj Should we fork json-snatcher?

**Comment by joshwnj** [comment]
@cap10morgan great idea.

Anyone want to volunteer to maintain a fork?

**Comment by cap10morgan** [comment]
@joshwnj How about this?

* I fork it and tag a release so MELPA Stable picks it up.
* I make you a collaborator on my fork in case you need anything changed / fixed in json-snatcher.
* You make json-mode dependent on my stable release.
* If the original json-snatcher author resurfaces, I'll happily discontinue my fork.
* If the original json-snatcher author does not resurface or is non-supportive of doing stable releases, my fork can continue. I likely won't do much with it, but I am happy to facilitate PRs (along w/ other interested collaborators who use the library).

Then the only outstanding question in my mind is: Should we change the name so we aren't squatting on it in MELPA Stable?

**Comment by joshwnj** [comment]
Sounds like a plan.

Do you know if there is any naming convention other people are using for cases like this? Eg. prefix something to the name to show it is a fork?

**Comment by cap10morgan** [comment]
I'm not aware of a convention, but I can research it. My first inclination would just be to prefix it with my GitHub username. So cap10morgan-json-snatcher.

**Comment by joshwnj** [comment]
Yeah that works for me

On Sunday, 15 November 2015, Wes Morgan <notifications@github.com> wrote:

> I'm not aware of a convention, but I can research it. My first inclination
> would just be to prefix it with my GitHub username. So
> cap10morgan-json-snatcher.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joshwnj/json-mode/issues/36#issuecomment-156744302>.
>


-- 
X-Team (http://x-team.com)

**Comment by cap10morgan** [comment]
[Good](https://github.com/Sterlingg/json-snatcher/issues/8#issuecomment-156885491) [news](https://github.com/Sterlingg/json-snatcher/releases/tag/1.0.0)!

**Comment by joshwnj** [comment]
Thanks for sharing this @cap10morgan - do you know whether I need to publish a new tag of `json-mode` now or is it just a matter of reinstalling?

At least according to http://stable.melpa.org/#/json-mode all dependencies are available within stable.melpa.org now.

**Comment by cap10morgan** [comment]
@joshwnj I'm still getting an error that the required version of json-reformat is unavailable (because MELPA date-based versions will almost always be far higher than typical / semantic version numbers found in MELPA Stable).

So I think you'd need to push a new release that depends on stable versions of all its deps.

**Comment by joshwnj** [comment]
I've pushed 1.6.0, appears to be working with melpa stable now. Can you please check? http://stable.melpa.org/#/json-mode

**Comment by cap10morgan** [comment]
:+1: Looks great. Thanks!
