### ISSUE TITLE
Can't enable json-mode for a buffer without a file

### ISSUE THREAD

**Issue by davazp** [joshwnj/json-mode#55]
If I invoke `json-mode` on a buffer without a file, I will get the following error

    Wrong type argument: stringp, nil

I use `json-mode` to display the answer of a server in [graphql-mode](https://github.com/davazp/graphql-mode), but it broke recently because of this.

**Comment by findtopher** [comment]
I think this may have been fixed - invoking json-mode in an empty buffer seems to work for me (using the current version of json-mode.el)

**Comment by davazp** [comment]
Indeed. It seems to work for me as well.
