### ISSUE TITLE
Integration with jq

### ISSUE THREAD

**Issue by Fuco1** [joshwnj/json-mode#57]
[jq](https://stedolan.github.io/jq/) is a popular tool to work with json.  You can query/filter/transform the documents using a very natural syntax.

Would you be interested in adding some integration of jq to json-mode?  I've written some functions for my personal use and I think this mode could benefit from it, I'm OK with doing the work and cleaning them up for a PR.  Obviously it depends on having jq installed but I think it's not extremely out of scope for this project---many major-modes integrate external tools into Emacs after all.

**Comment by joshwnj** [comment]
@Fuco1 nice idea. My feeling is that it's probably better to keep `json-mode` light, and add `jq` support as a separate package that depends on `json-mode`. What do you think about that?

**Comment by Fuco1** [comment]
In the meantime I've found this https://github.com/ljos/jq-mode which I think covers it.  Maybe a mention in the readme would be enough, I've been using it and it is pretty solid.

**Comment by joshwnj** [comment]
Nice, thanks!
